language: node_js
node_js:
    - 12
cache:
    apt: true
    directories:
        - node_modules
jobs:
    include:
        - stage: master
          name: "master"
          if: branch = master
          before_script:
              - export TZ='Asia/Shanghai'
              - npm run build
              - npm run docs
          script:
              - git remote -v
              - git config user.name "Travis CI"
              - git config user.email "travis.ci@spiritling.pub"
              - git checkout --orphan release
              - git branch -v -a
              - git rm --cached -r -f ./dist
              - rm -rf ./src
              - rm -rf ./test
              - git add -f .
              - git commit -m "Travis CI Auto Release"
              - git push -f https://${GITHUB_USERNAME}:${GITHUB_WRITE_TOKEN}@github.com/SpiritLingBasic/library.git
        - stage: dev
          name: "dev"
          if: branch = dev
          before_script:
              - export TZ='Asia/Shanghai' # 改变时区
          script:
              - git remote -v
              - git config user.name "Travis CI"
              - git config user.email "travis.ci@spiritling.pub"
              - git checkout --orphan release
              - git branch -v -a
              - git rm --cached -r -f ./dist
              - rm -rf ./src
              - rm -rf ./test
              - git add -f .
              - git commit -m "Travis CI Auto Release"
              - git push -f https://${GITHUB_USERNAME}:${GITHUB_WRITE_TOKEN}@github.com/SpiritLingBasic/library.git

notifications:
    email:
        recipients:
            - travis.ci@spiritling.pub
        on_success: never # default: change
        on_failure: always # default: always
